### ISSUE TITLE
Doesn't support Omega 2 Plus

### ISSUE THREAD

**Issue by ryanteck** [plan44/plan44-feed#1]
Currently doesn't support Omega 2 Plus.

Trying to compile for the ttngw firmware.

How easy is it to change to compile for + versions?

**Comment by plan44** [comment]
It *should* just work, when you select Omega2+ in menuconfig as target. What are the problems you are experiencing?

I do not have any Omega2+ experience myself - Omega2+ cannot reliably reboot without power cycling and thus is IMHO not suitable for remotely managed 24/7 gadgets...

**Comment by ryanteck** [comment]
I managed to compile it all in the end however still didn't work. Also didn't know about the remote reboot thing.

You can close this if you like as I'm returning my O2+ to the retailer as it's just too buggy for a gateway. Trying out another SBC.

Thanks and sorry about the hassle.

**Comment by plan44** [comment]
Note that the *standard* Omega2 is perfectly fine regarding reboot. It's the bigger flash in the *plus* variant that causes the problem due to an addressing schema incompatibility between MT7688 and the particular flash chip Onion chose.
My experience with hundreds of Omega2 based devices in the field, is that it is working very reliably for 24/7.

**Comment by ryanteck** [comment]
Might look at replacing it with a standard omega2 and report back. Will see.
